services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    restart: no
    container_name: zookeeper
    ports:
      - '2181:2181'
    enviroment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - zookeeper:/bitnami/zookeeper
    networks:
      - ms-issue-network
  
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    restart: no
    container_name: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    enviroment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ADVERTISED_HOST_NAME: kafka-internal.io
    volumes:
      - kafka:/bitnami/kafka
    networks:
      - ms-issue-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: no
    container_name: kafka-ui
    ports:
      - 8080:8080
    enviroment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - ms-issue-network
    depends_on:
      - kafka

networks:
  ms-issue-network:
    driver: bridge

volumes:
  zookeeper: {}
  kafka: {}
